from .galaxy_zoo_simclr_trainer import GalaxyZooSimCLRTrainer
from .galaxy_zoo_classifier_trainer import GalaxyZooClassifierTrainer
from .galaxy_zoo_conditional_generator import GalaxyZooConditionalGeneratorTrainer
