batch_size: 128    # batch size to use, when training generator
n_workers: 16      # number of workers in dataloader
lr: 1e-4           # learning rate. Do not remove this line

fine_tune_from: # path to model, to fine tune from

loss: lsgan  # type of loss to use. Options: 'hinge', 'non_saturating' and 'lsgan'. Do not remove this line

dataset:            # dataset parameters
  name: galaxy_zoo  # dataset name
  path: /home/kinakh/Datasets/galaxy-zoo-the-galaxy-challenge/images_training_rev1/ # path to folder with images
  anno: /home/kinakh/Datasets/galaxy-zoo-the-galaxy-challenge/training_solutions_rev1.csv # path to file with attribute annotations
  size: 64          # image size
  n_out: 37         # number of attributes for each image
  n_channels: 3     # number of channels in image

encoder:                                   # encoder parameters
  path: ./models/GalaxyZoo/galaxy_zoo.pth  # path to pretrained encoder model
  base_model: resnet50                     # encoder base model
  out_dim: 128                             # z-projection size

classifier:                                           # classifier parameters
  path: ./models/GalaxyZoo/galaxy_zoo_classifier.pth  # path to pretrained classifier model
  n_features: 2048                                    # number of input features in the classifier model

generator:             # generator parameters
  z_size: 512          # z vector size
  n_basis: 6           # size of the z1, ... zk input variables
  noise_size: 512      # size of the generator input (generator input is attributes mixed with z vector sampled from N(0, 1))
  y_type: real         # type of attributes

discriminator:    # discriminator parameters
  type: patch     # type of discriminator. Choices: 'global' and 'patch'
  actnorm: False
  ndf: 64
  n_layers: 4

eval:
  path_encoder: ./models/cVAE/parameter_state_dict_Encoder.pth

comment: galaxy_zoo_generation_baseline
