batch_size: 64        # batch size to use, when training generator
epochs: 250           # number of total training steps
cls_reg_every: 8      # how often to apply classification regularization (steps)
d_reg_every: 16       # how often to apply d regularization (steps)
d_reg: 10.0           # d regularization parameter
orth_reg: 100.0       # generator orthogonal regularization parameter

save_every: 10       # how often to save the model (epochs)
log_every: 100       # how often to log losses to tensorboard (steps)
sample_every: 500    # how often to save generated images (steps)
n_workers: 16        # number of workers in dataloader
lr: 1e-4             # learning rate
fid: True            # if True, then FID will be calculated when saving checkpoint model

fine_tune_from:      # path to model, to fine tune from

loss: lsgan  # type of loss to use. Options: 'hinge', 'non_saturating' and 'lsgan'

dataset:            # dataset parameters
  name: galaxy_zoo  # dataset name
  path: <>          # path to folder `images_training_rev1` with images
  anno: <>          # path to file `training_solutions_rev1.csv` with attribute annotations
  size: 64          # image size
  n_out: 37         # number of attributes for each image
  n_channels: 3     # number of channels in image

encoder:                                   # SimCLR encoder parameters
  path: ./models/GalaxyZoo/galaxy_zoo.pth  # path to pretrained encoder model
  base_model: resnet50                     # encoder base model
  out_dim: 128                             # z-projection size

classifier:                                           # classifier, which used for generator training
  path: ./models/GalaxyZoo/galaxy_zoo_classifier.pth  # path to pretrained classifier model
  n_features: 2048                                    # number of input features in the classifier model

generator:             # generator parameters
  z_size: 512          # z vector size
  n_basis: 6           # size of the z1, ... zk input variables
  noise_size: 512      # size of the generator input (generator input is attributes mixed with z vector sampled from N(0, 1))
  y_type: real         # type of attributes

discriminator:    # discriminator parameters
  type: patch     # type of discriminator. Choices: 'global' and 'patch'
  actnorm: False
  ndf: 64
  n_layers: 4

eval:           # evaluation parameters
  path_encoder: ./models/cVAE/parameter_state_dict_Encoder.pth   # path to autoencoder, used for evaluation
  n_clusters: 10                                                  # number of clusters used for evaluation
  path_classifier: ./models/classifier/parameter_state_dict_ImageClassifier.pth   # path to classifier for evaluation

comment: galaxy_zoo_generation
