batch_size: 64        # batch size to use, when training generator
path_image: ./images/100765.jpg
n_workers: 16

dataset:            # dataset parameters
  name: galaxy_zoo  # dataset name
  path: <>          # path to folder with images
  anno: <>          # path to file with attribute annotations
  size: 64          # image size
  n_out: 37         # number of attributes for each image
  n_channels: 3     # number of channels in image

encoder:                                   # SimCLR encoder parameters
  path: ./models/GalaxyZoo/galaxy_zoo.pth  # path to pretrained encoder model
  base_model: resnet50                     # encoder base model
  out_dim: 128                             # z-projection size

autoencoder:                                              # autoencoder, used for evaluation
    path: ./models/cVAE/parameter_state_dict_Encoder.pth  # path to autoencoder model

classifier:   # classifier, used for attribute control accuracy
    path: ./models/classifier/parameter_state_dict_ImageClassifier.pth

n_clusters: 10  # number of cluster for cluster features

comment: single_image_eval