batch_size: 64        # batch size to use, when training generator
path_image: ./images/100765.jpg
n_workers: 16

dataset:            # dataset parameters
  name: galaxy_zoo  # dataset name
  path: /home/kinakh/Datasets/galaxy-zoo-the-galaxy-challenge/images_training_rev1/ # path to folder with images
  anno: /home/kinakh/Datasets/galaxy-zoo-the-galaxy-challenge/training_solutions_rev1.csv # path to file with attribute annotations
  size: 64          # image size
  n_out: 37         # number of attributes for each image
  n_channels: 3     # number of channels in image

encoder:                                   # encoder parameters
  path: ./models/GalaxyZoo/galaxy_zoo.pth  # path to pretrained encoder model
  base_model: resnet50                     # encoder base model
  out_dim: 128                             # z-projection size

autoencoder:
    path: ./models/cVAE/parameter_state_dict_Encoder.pth

classifier:
    path: ./models/classifier/parameter_state_dict_ImageClassifier.pth

n_clusters: 5

comment: single_image_eval